{"name": "Авторизация с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1720183747463, "stop": 1720183747730}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1720183747730, "stop": 1720183747806}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1720183747806, "stop": 1720183747812}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1720183747463, "stop": 1720183747812, "uuid": "f5f06ccd-0746-42e7-becd-c4582f4434a3", "historyId": "d8a40f37ba9e4ebb3e974150455e73a8", "testCaseId": "75bc51d029e4608920585d699e2de0b6", "fullName": "tests.test_login_page#test_login_failure", "labels": [{"name": "feature", "value": "Авторизация"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "rain"}, {"name": "thread", "value": "23880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_page"}]}